# api-gateway Dockerfile
FROM eclipse-temurin:11-jre
ARG PROJECT_VERSION=0.1.0
RUN mkdir -p /home/app
WORKDIR /home/app

ENV SPRING_PROFILES_ACTIVE dev

COPY . .
# JAR del microservicio
# ADD target/api-gateway-v${PROJECT_VERSION}.jar api-gateway.jar
ADD target/*.jar api-gateway.jar

# Puerto de exposición
EXPOSE 8080

ENTRYPOINT ["java", "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}", "-jar", "api-gateway.jar"]
