pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "shammery/api-gateway"
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Build & Test') {
            steps {
                script {
                    docker.image('maven:3.8.4-openjdk-11').inside('-v $PWD:/workspace -w /workspace/api-gateway') {
                        sh 'mvn clean test package -DskipTests=false'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE:latest api-gateway/'
            }
        }

        stage('Login & Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    retry(3) {
                        sh "docker push shammery/api-gateway:latest"
                    }
                }
            }
        }
    }
}
